export { DeleteAvatar } from './DeleteAvatar'
export { EditAvatar } from './EditAvatar'
export { EditEmail } from './EditEmail'
export { EditInfo } from './EditInfo'
export { EditPassword } from './EditPassword'
export { EditPhone } from './EditPhone'
export { ViewAvatar } from './ViewAvatar'
