export const colors = {
  statusDanger: '#FF3300',
  statusLightSuccess: '#5BBC5D',
  statusLightWarning: '#E0A309',
  statusLightDanger: '#BC5BB9',
  statusLightPrimary: '#617AF1',
  statusLightSurfaceSuccess: '#EEF7ED',
  statusLightSurfaceDanger: '#FCEDEB',
  statusLightSurfacePrimary: '#F4F5FE',

  lightInProgress: '#E9FBE9',
  darkInProgress: '#134D13',
  lightWaiting: '#FBF2E9',
  lightWarning: '#FFFCF5',
  darkWaiting: '#4C3013',
  lightDenied: '#FBE9E9',
  darkDenied: '#4C1313',
  lightRouter: '#E9E9FB',
  darkRouter: '#13134D',
  lightQueue: '#F2E9FB',
  darkQueue: '#30134D',
  lightML: '#E9FBFB',
  darkML: '#134D4D',
  inputBorderColor: '#D4D3D5',
}
